apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner-artur
  namespace: github-runner
spec:
  replicas: 1
  template:
    spec:
      repository: Slamparty/github-learn
      serviceAccountName: default
      labels:
        - build
        - push
        - k8s