name: Build and Deploy to GKE
on:
  push:
    branches:
      - main
env:
  REPO: us-east1-docker.pkg.dev/calcium-market-373517/ysys-staging-container-registry
  IMAGE_TAG: ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
  CONTEXT: "gcloud-kubectl-helm/"
  DOCKERFILE: "gcloud-kubectl-helm/Dockerfile"
  IMAGE: "gcloud-kubectl-helm"

jobs:
   build:
    runs-on: ysys

    steps:
     - name: kaniko
       run: |-
          echo $(pwd)
          docker run \
          gcr.io/kaniko-project/executor:latest \
          --context "${CONTEXT}" \
          --dockerfile https://github.com/Slamparty/github-learn/tree/a0d223e99528e7b92aee0beed3fe8820d8c6f486/gcloud-kubectl-helm/Dockerfile \
          --destination "$REPO/$IMAGE:0.0" \
          --destination "$REPO/$IMAGE:latest"