name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  PUBLIC_REPO: europe-central2-docker.pkg.dev/docker-396214/gitlab-k8s
  IMAGE_TAG: ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
  CONTEXT: "github-learn/gcloud-kubectl-helm/"
  DOCKERFILE: "Dockerfile"
  IMAGE: "gcloud-kubectl-helm"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Kaniko
      uses: gcr.io/kaniko-project/executor:v1.17.0-debug
      script: 
      - /kaniko/executor
       --context "${CONTEXT}"
       --dockerfile "${DOCKERFILE}"
       --destination "$PUBLIC_REPO/$IMAGE:$IMAGE_TAG"
       --destination "$PUBLIC_REPO/$IMAGE:latest"

      
