name: Build and Deploy to GKE
on:
  push:
    branches:
      - main
env:
  PUBLIC_REPO: us-central1-docker.pkg.dev/useful-art-405022/github-repo
  IMAGE_TAG: ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
  CONTEXT: "gcloud-kubectl-helm/"
  DOCKERFILE: "gcloud-kubectl-helm/Dockerfile"
  IMAGE: "gcloud-kubectl-helm"

jobs:
   build:
    runs-on: self-hosted

    steps:
     - name: kaniko
       run: |-
          echo $(pwd)
          docker run \
          gcr.io/kaniko-project/executor:latest \
          --context "${CONTEXT}" \
          --dockerfile https://github.com/Slamparty/github-learn/tree/a0d223e99528e7b92aee0beed3fe8820d8c6f486/gcloud-kubectl-helm/Dockerfile \
          --destination "$PUBLIC_REPO/$IMAGE:0.0" \
          --destination "$PUBLIC_REPO/$IMAGE:latest"
      
      #- uses: int128/kaniko-action@v1
      #- uses: aevea/action-kaniko@master
      #- name: build
      #  run: |-
      #    /kaniko/executor
      #    --context "${CONTEXT}"
      #    --dockerfile "${DOCKERFILE}"
      #    --destination "$PUBLIC_REPO/$IMAGE:$IMAGE_TAG"
      #    --destination "$PUBLIC_REPO/$IMAGE:latest"
      # push-psuh
    
        
        # with:
        #   build_file: "${DOCKERFILE}"
        #   registry: "$PUBLIC_REPO"
        #   image: "$PUBLIC_REPO/$IMAGE:$IMAGE_TAG"
